language: ruby
sudo: false
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.bundle
rvm:
  - 2.3.1
  - 2.2.5
  - jruby-head
  - rbx
env:
  # recognized by czmq-ffi-gen's ci-scripts
  - CZMQ_VERSION=HEAD ZMQ_VERSION=HEAD
matrix:
  allow_failures:
    - rvm: rbx
before_install:
  - PATH="/usr/lib/ccache:$PATH" # enable ccache
  - export LD_LIBRARY_PATH=$HOME/lib # custom libs (for execution)
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig # custom libs (for linking)
  - export BUNDLE_PATH=$HOME/.bundle # bundle caching
  - ci-scripts/install-deps
  - gem install bundler -v 1.10.6
script: bundle exec rake spec
